import json


def to_script(filename, outfile, token="#script"):
    """Convert a jupyter notebook to a python script.
    :param filename Path to the jupyter notebook file
    :param outfile Path of the target output script file
    :param token String token to be set of each cell of the notebook, that is to be copied"""
    with open(filename, "r") as f:
        j = json.load(f)

    # Start generated script file with a warning comment
    code = "# This is autogenerated code from " + filename + ". Do not modify!\\n\\n"

    for cell in j["cells"]:
        if cell["cell_type"] == "code":
            if len(cell["source"]) > 1 and token in cell["source"][0]:
                # Append all code lines in a selected cell with two blank lines
                for row in cell["source"][1:]:
                    code += row,
                code += "\\n\\n"

    with open(outfile, "w") as f:
        f.write(code)
