import json
import os


def to_script(nbpath, outpath, token="#script"):
    """Convert a jupyter notebook to a python script.
    :param nbpath Path to the jupyter notebook file
    :param outpath Path of the target output script file
    :param token String token to be set of each cell of the notebook, that is to be copied"""
    with open(nbpath, "r") as f:
        j = json.load(f)

    # Start generated script file with a warning comment
    code = "# This is autogenerated code from " + nbpath + ". Do not modify!\\n\\n"

    for cell in j["cells"]:
        if cell["cell_type"] == "code":
            if len(cell["source"]) > 1 and token in cell["source"][0]:
                # Append all code lines in a selected cell with two blank lines
                for row in cell["source"][1:]:
                    code += row,
                code += "\\n\\n"

    # Some path and file name checking
    outpath, outfile = os.path.split(outpath)
    os.mkdirs(outpath, exists_ok=True)

    if outfile == "":
        outfile = "script.py"
    elif ".py" not in outfile:
        outfile += ".py"

    # Finally write code to outfile
    with open(os.path.join(outpath, outfile), "w") as f:
        f.write(code)
